services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mean-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/testdb --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: preetam8055/mean-backend:latest
    container_name: backend
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongodb:27017/testdb
    ports:
      - "8080:8080"
    networks:
      - mean-net

  frontend:
    image: preetam8055/mean-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mean-net

networks:
  mean-net:
